name: Bump version
on:
  push: 
    branches: 
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  bump:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v0.1.1',
              sha: context.sha
            })
