name: Bump version
on:
  push: 
    branches: 
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  bump:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calculate version
        id: calculate_version
        run: |
          echo $(git tag)
          NEW_VERSION=$(git tag | grep frontend/v | sed -e "s/^frontend\/v/1 + /" | bc)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
      - name: Display all outputs as JSON
        run: |
          echo "${{ toJSON(steps.calculate_version.outputs) }}"

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.calculate_version.outputs.new_version }}',
              sha: context.sha
            })
